manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: urob # or zmkfirmware, see comment below
      revision: v0.2+fix-child-nodes
      import: app/west.yml
    - name: zmk-adaptive-key
      remote: urob
      revision: v0.2 # set to same as ZMK version above
  self:
    path: config
